# wrangler.toml
name = "mybookai"
main = "worker/index.js"
compatibility_date = "2024-01-01" # Keep your compatibility date

# This is the correct way to serve static assets with env.ASSETS
[assets]
binding = "ASSETS"
directory = "./dist" # This matches your "bucket" path

[vars]
ENVIRONMENT = "production"

[build]
command = "npm run build"

[dev]
port = 8787
local_protocol = "http"

[observability.logs]
enabled = true