# wrangler.toml
name = "mybookai"
main = "worker/index.js"
compatibility_date = "2024-01-01" # Or a newer date

# R2 Buckets
[[r2_buckets]]
binding = "MYBOOK_INPUT_BUCKET" # Name of the R2 bucket binding in your Worker
bucket_name = "mybook-input-files" # Name of your R2 bucket

[[r2_buckets]]
binding = "MYBOOK_OUTPUT_BUCKET" # Name of the R2 bucket binding in your Worker
bucket_name = "mybook-output-books" # Name of your R2 bucket

# Durable Objects
[durable_objects]
MYBOOK_JOB_MANAGER = { class_name = "BookJobManager", script_name = "mybookai" }

# Queues
[[queues.producers]]
binding = "MYBOOK_JOB_QUEUE" # Name of the Queue binding in your Worker
queue = "mybook-job-queue" # Name of your Cloudflare Queue

# Workers AI
[[ai]]
binding = "AI" # Name of the AI binding in your Worker

[build]
command = "npm run build" # Command to build your frontend (e.g., React app)

[dev]
port = 8787
local_protocol = "http"

[observability.logs]
enabled = true

# AI Processor Worker
[[workers_for_platforms]]
name = "mybookai-ai-processor"
main = "ai-processor-worker/index.js"
compatibility_date = "2024-01-01"

# Bindings for AI Processor Worker
[workers_for_platforms.r2_buckets]
MYBOOK_INPUT_BUCKET = "mybook-input-files"
MYBOOK_OUTPUT_BUCKET = "mybook-output-books"

[workers_for_platforms.durable_objects.MYBOOK_JOB_MANAGER]
script_name = "mybookai"
class_name = "BookJobManager"

[workers_for_platforms.queues.consumers.MYBOOK_JOB_QUEUE]
queue = "mybook-job-queue"

[workers_for_platforms.ai]
binding = "AI"
